# HTTP
http:
  port: 5381
  adminPort: 5382
  rootPath: "/api/*"

  # HTTP request log settings.
  requestLog:

    # Settings for logging to stdout.
    console:

      # If true, log requests to stdout.
      enabled: false

    # Settings for logging to a file.
    file:

      # If true, log requests to a file.
      enabled: false

# Controls generation of "Last-Modified" and "ETag" HTTP headers
cache:
  enabled: true

  # Enable Last-Modified HTTP header generation
  enableLastModified: true

  # List of resources for which Last-Modified HTTP header should not be generated. Format: regex accepted by java.lang.String
  excludeLastModified: ["^v\\d+/short$", "^v\\d+/auth/.*$", "^v\\d+/download.*$"]

  # Enable ETag HTTP header generation
  enableETag: false

  # List of resources for which ETag HTTP header should not be generated. Format: regex accepted by java.lang.String
  excludeETag: []

# Authentication
crowd:
  ssoUrl: "https://***REMOVED***/user?continue="

hazelcast:
  # NB: Below hazelcast settings do not have default values. The portal won't start if they're unset

  # Credentials to enter a group. E.g. dev, uat, prod groups
  groupName: "dcc-prod"
  groupPassword: "DccProdPasswd"

  # Time-to-live settings.
  # Maximum number of seconds for each entry to stay in the cache. Entries that are
  # older than the set value and not updated for that time
  # will get automatically evicted from the cache.

  # Expire inactive users in 15 minutes
  usersCacheTTL: 900

  # Expire openId authentication attempt in 2 minutes
  openidAuthTTL: 120

# ElasticSearch index and hosts
elastic:
  indexName: "dcc-release-dcc-etl-cli"
  nodeAddresses:
     - host: "localhost"
       port: 9300

# Mail
mail:
  enabled: false
  recipientEmail: ***REMOVED***

# Genomemaps
browser:
  dataSources:
     - uri: gene
       className: org.icgc.dcc.portal.browser.ds.GeneDataSource
     - uri: mutation
       className: org.icgc.dcc.portal.browser.ds.MutationDataSource

# Data download
download:
  enabled: true
  uri: "hdfs://<namenode>:8020"
  dynamicRootPath: "/icgc/download/dynamic"
  staticRootPath: "/icgc/download/static"
  currentReleaseSymlink: "/Current /dev-06e-6-31"
  stage: "PRODUCTION"
  quorum: "localhost"
  oozieUrl: "http://***REMOVED***:11000/oozie"
  appPath: "***REMOVED***/user/downloader/workflows/archive-main"
  releaseName: "CURRENT_RELEASE"

web:
  # Defines an external URL when the portal is behind a reverse proxy / load balancer. E.g. shortUrl resource uses it for generation of valid URLs
  baseUrl: "https://dcc.icgc.org"

# Logging settings
logging:

  # Settings for logging to stdout.
  console:

    # If true, write log statements to stdout.
    enabled: true

  # Settings for logging to a file.
  file:

    # If true, write log statements to a file.
    enabled: false

    # Do not write log statements below this threshold to the file.
    threshold: INFO

    # The file to which current statements will be logged.
    currentLogFilename: ../logs/dcc-portal-api.log

    # When the log file rotates, the archived log will be renamed to this and gzipped. The
    # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
    # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
    archivedLogFilenamePattern: ../logs/dcc-portal-api-%d.log.gz

    # The number of archived files to keep.
    archivedFileCount: 10

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL
  level: INFO

  # Logger-specific levels
  loggers:

    # Jersey request logging
    "com.sun.jersey.api.container.filter.LoggingFilter": INFO

    # ElasticSearch query logging
    "org.icgc.dcc.portal.service.BaseQueryService": WARN

    # Very chatty
    "com.wordnik.swagger.jsonschema.ApiModelParser": WARN

    # dynamic downloader logging
    "org.apache.hadoop.hbase": WARN
    "org.apache.zookeeper": WARN

    # ERRORs should be converted to WARNs in Swagger 1.2.2
    "com.wordnik.swagger.jaxrs.HelpApi": OFF

# ICGC Client configuration
icgc:

  # CGP/DACO API endpoint
  cgpUrl: "https://***REMOVED***/ud_oauth/1/search"

  # ShortUrl API endpoint
  shortUrl: "https://***REMOVED***/short/api/1/shorten"

  # CUD API endpoint
  cudUrl: "https://***REMOVED***/ud_rest/1"

  # CUD credentials. Obtained from webdev@oicr.on.ca
  cudAppId: ""
  cudUser: ""
  cudPassword: ""

  # OAuth credentials
  # To generate the credentials go to icgc.org, log in, go to the "OAuth Settings" tab and request "Regenerate all tokens"
  consumerKey: "***REMOVED***"
  consumerSecret: "***REMOVED***"
  accessToken: "***REMOVED***"
  accessSecret: "***REMOVED***"

  # Log HTTP requests to the API
  enableHttpLogging: false

  # Disallow self-signed SSL certificates
  enableStrictSSL: true

release:
  releaseDate: "placeholder"